### ISSUE TITLE
No such file or directory: '../GoogleNews-vectors-negative300.bin'

### ISSUE THREAD

**Issue by chchenhui** [UVa-NLP/VMASK#3]
Hi, 

I have encountered an error when trying to run the codes. It seems the codes need the file '../GoogleNews-vectors-negative300.bin' but I can't find it. Could you please kindly provide it?

Thanks,

**Comment by HanjieChen** [comment]
Hi,

You can download the word2vec: https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
